services:
  app:
    build: ./
    container_name: posts_and_comments_service
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service
    environment:
      USE_IN_MEMORY: "false"
    networks:
      - posts_net


  postgres:
    image: postgres:16
    container_name: posts_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U yks" ]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      posts_net:
        aliases:
          - database

  migrate:
    image: panitz/goose:latest
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    command: ["goose", "internal/db/migrations",  "GOOSE_DBSTRING=postgresql://postgres:password@127.0.0.1/go_migrations?sslmode=disable", "up" ]
    depends_on:
      postgres:
        condition: service



